### ISSUE TITLE
Not auto import but removed used import

### ISSUE THREAD

**Issue by m0n203** [incu6us/goimports-reviser#166]
I am using `helix 24.7` and `goimports-reviser 3.8.2`, with configuration:
```toml
[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports-reviser", args = ["-rm-unused", "-set-alias", "-format", "-"] }
```

Am I doing it wrong?

[Screencast_20241128_104856.webm](https://github.com/user-attachments/assets/f907b4a6-6932-41c3-a7e2-bea1e33cf53a)
